/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dankest_dungeon;
import javax.swing.ImageIcon; 
/**
 *
 * @author Michiel Proost
 */
public class FrameDungeon extends javax.swing.JFrame {
    public int menu=1; //start bij het exploration menu
    /**
     * Creates new form FrameDungeon
     */
    public FrameDungeon() {
        initComponents();
        start();
    }
    
    public void start(){ //start van het spel
        Player player = new Player();
        ProgressBarHP.setValue(player.hp);
        String strenght = "" + player.strength;
        TextFieldStrenght.setText(strenght);
        String score = "" + player.score;
        TextFieldScore.setText(score);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelStats = new javax.swing.JPanel();
        HPLabel = new javax.swing.JLabel();
        ProgressBarHP = new javax.swing.JProgressBar();
        StrenghtLabel = new javax.swing.JLabel();
        TextFieldStrenght = new javax.swing.JTextField();
        ScoreLabel = new javax.swing.JLabel();
        TextFieldScore = new javax.swing.JTextField();
        LootButton = new javax.swing.JButton();
        MoveButton = new javax.swing.JButton();
        QuitButton = new javax.swing.JButton();
        BagButton = new javax.swing.JButton();
        PanelScherm = new javax.swing.JPanel();
        PictureLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 204));
        setMinimumSize(new java.awt.Dimension(1920, 1080));

        PanelStats.setBackground(java.awt.SystemColor.controlLtHighlight);
        PanelStats.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        PanelStats.setPreferredSize(new java.awt.Dimension(960, 240));

        HPLabel.setText("HP");

        ProgressBarHP.setStringPainted(true);
        ProgressBarHP.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ProgressBarHPStateChanged(evt);
            }
        });

        StrenghtLabel.setText("Strenght");

        TextFieldStrenght.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldStrenghtActionPerformed(evt);
            }
        });

        ScoreLabel.setText("Score");

        TextFieldScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldScoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelStatsLayout = new javax.swing.GroupLayout(PanelStats);
        PanelStats.setLayout(PanelStatsLayout);
        PanelStatsLayout.setHorizontalGroup(
            PanelStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelStatsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StrenghtLabel)
                    .addComponent(HPLabel)
                    .addComponent(ScoreLabel))
                .addGap(59, 59, 59)
                .addGroup(PanelStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(TextFieldStrenght, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TextFieldScore, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                    .addComponent(ProgressBarHP, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(302, Short.MAX_VALUE))
        );
        PanelStatsLayout.setVerticalGroup(
            PanelStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelStatsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProgressBarHP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HPLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StrenghtLabel)
                    .addComponent(TextFieldStrenght, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ScoreLabel)
                    .addComponent(TextFieldScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        LootButton.setText("LOOT");
        LootButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LootButtonActionPerformed(evt);
            }
        });

        MoveButton.setText("MOVE");
        MoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoveButtonActionPerformed(evt);
            }
        });

        QuitButton.setText("QUIT");
        QuitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitButtonActionPerformed(evt);
            }
        });

        BagButton.setText("BAG");
        BagButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BagButtonActionPerformed(evt);
            }
        });

        PanelScherm.setBackground(new java.awt.Color(153, 153, 153));

        PictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dankest_dungeon/Layout.png"))); // NOI18N
        PictureLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout PanelSchermLayout = new javax.swing.GroupLayout(PanelScherm);
        PanelScherm.setLayout(PanelSchermLayout);
        PanelSchermLayout.setHorizontalGroup(
            PanelSchermLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PictureLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelSchermLayout.setVerticalGroup(
            PanelSchermLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSchermLayout.createSequentialGroup()
                .addComponent(PictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelStats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BagButton, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LootButton, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(PanelScherm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PanelScherm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LootButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(QuitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BagButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(PanelStats, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldScoreActionPerformed
        //nog te maken
    }//GEN-LAST:event_TextFieldScoreActionPerformed

    private void LootButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LootButtonActionPerformed
        switch(menu){
            case 1: ChangeButtons(4);
                    menu = 4;
                    break;
            case 2: ChangeButtons(5);
                    menu = 5;
                    break;
            case 4: ChangeButtons(1);
                    menu = 1;
                    break;
            case 5: ChangeButtons(3);
                    menu = 1;
                    break;
        }
    }//GEN-LAST:event_LootButtonActionPerformed

    private void TextFieldStrenghtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldStrenghtActionPerformed
        //nog te maken
    }//GEN-LAST:event_TextFieldStrenghtActionPerformed

    private void MoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoveButtonActionPerformed
        int doors=3;
        switch (menu){
            case 1: {
                ChangeButtons(2); //naar het move menu
                menu = 2;
                switch(doors){
                    case 1: ImageIcon icon = change("Layout.png");
                            PictureLabel.setIcon(icon);
                            break;
                    case 2: icon = change("DoorToTheRight.png");
                            PictureLabel.setIcon(icon);
                            break;
                    case 3: icon = change("Layout.png");
                            PictureLabel.setIcon(icon);
                            break;
                    case 4: icon = change("MaximumDoors.png");
                            PictureLabel.setIcon(icon);
                            break;
                }
                break;
            }
            case 2: ChangeButtons(5);
                    menu = 5;
                    break;
        }
      
    }//GEN-LAST:event_MoveButtonActionPerformed

    private void QuitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitButtonActionPerformed
        switch(menu){
            case 1: System.exit(0);
            case 2: ChangeButtons(5);
                    menu = 5;
                    break;
            case 3: ChangeButtons(1);
                    menu = 1;
                    break;
            case 5: ChangeButtons(1);
                    menu = 1;
                    break;
        }
    }//GEN-LAST:event_QuitButtonActionPerformed

    private void BagButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BagButtonActionPerformed
        switch (menu){
            case 1: ChangeButtons(3);
                    menu = 3;
                    break;
            case 2: ChangeButtons(5);
                    menu = 5;
                    break;
        }
    }//GEN-LAST:event_BagButtonActionPerformed

    private void ProgressBarHPStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ProgressBarHPStateChanged
        //nog te maken
    }//GEN-LAST:event_ProgressBarHPStateChanged
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDungeon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDungeon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDungeon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDungeon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrameDungeon().setVisible(true);
            }
        });
        
    }
    
    public ImageIcon change(String string){
        ImageIcon icon = new ImageIcon(string);
        return icon;
    }
    
    public void ChangeButtons(int menu){
        switch(menu){
            case 1: { //exploration menu
                MoveButton.setText("MOVE");
                LootButton.setText("LOOT");
                BagButton.setText("BAG");
                QuitButton.setText("QUIT");
                break;
            }
            case 2: { //move menu
                MoveButton.setText("UP");
                LootButton.setText("DOWN");
                BagButton.setText("RIGHT");
                QuitButton.setText("LEFT");
                break;
            }
            case 3: { //inventory menu
                MoveButton.setText("USE");
                LootButton.setText("DROP");
                BagButton.setText("");
                QuitButton.setText("EXIT");
                break;
            }
            case 4: { //loot menu
                MoveButton.setText("PICK");
                LootButton.setText("EXIT");
                BagButton.setText("");
                QuitButton.setText("");
                break;
            }
            case 5: { //combat menu
                MoveButton.setText("ATTACK");
                LootButton.setText("BAG");
                BagButton.setText("");
                QuitButton.setText("RUN");
            }    
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BagButton;
    private javax.swing.JLabel HPLabel;
    private javax.swing.JButton LootButton;
    private javax.swing.JButton MoveButton;
    private javax.swing.JPanel PanelScherm;
    private javax.swing.JPanel PanelStats;
    private javax.swing.JLabel PictureLabel;
    private javax.swing.JProgressBar ProgressBarHP;
    private javax.swing.JButton QuitButton;
    private javax.swing.JLabel ScoreLabel;
    private javax.swing.JLabel StrenghtLabel;
    private javax.swing.JTextField TextFieldScore;
    private javax.swing.JTextField TextFieldStrenght;
    // End of variables declaration//GEN-END:variables
}
